"""Pipeline CLI — runs the 4-phase loop: Plan -> Execute -> Verify -> Review.

Usage:
    python pipeline.py "Add /api/stats endpoint"
    python pipeline.py "Build Mostaql scraper"
    python pipeline.py --loop 3  # Run 3 iterations

Phases:
    1. Planning   -> plan.md
    2. Execution  -> changed files
    3. Verification -> verify_report.md (PASS/FAIL)
    4. Review     -> review_report.md + new skills

Loop: if verification FAILS, loop back to execution up to N times.
"""
import os
import sys
import json
import subprocess
from datetime import datetime
from pathlib import Path

ROOT = Path("C:/Users/A/Desktop/Money")
ENGINE_DIR = ROOT / "ai-automation-engine"
PLANS_DIR = ROOT / "plans"
PLANS_DIR.mkdir(exist_ok=True)

PYTHON = "C:/Users/A/AppData/Local/Programs/Python/Python312/python.exe"


def log(msg):
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


def phase_1_planning(task):
    """Generate plan.md using AI gateway."""
    log(f"PHASE 1: Planning — {task}")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    plan_path = PLANS_DIR / f"plan_{timestamp}.md"

    system = (
        "You are a planning assistant for Salim Muhammad, AI Automation Engineer. "
        "Generate a structured plan.md for the given task. Include sections: "
        "Goal, Context, Steps, Files to Modify, Verification Criteria, Risks. "
        "Be concise, specific, and actionable. No fluff."
    )
    user_prompt = f"Task: {task}"

    try:
        sys.path.insert(0, str(ROOT))
        from keyhub_client import ai_generate
        content = ai_generate(user_prompt, system=system, caller="pipeline.py")
    except Exception as e:
        log(f"  AI failed ({e}) — using template fallback")
        content = generate_template_plan(task)

    plan_path.write_text(content, encoding="utf-8")
    log(f"  -> {plan_path}")
    return plan_path


def generate_template_plan(task):
    """Fallback plan template if AI unavailable."""
    return f"""# Plan: {task}

**Date:** {datetime.now().isoformat()}
**Author:** Salim Muhammad (via Pipeline CLI)
**Phase:** 1 of 4 (Planning)

---

## 1. Goal
{task}

## 2. Context
Generated by template (AI unavailable).

## 3. Steps
1. Analyze the task
2. Identify files to create/modify
3. Implement
4. Verify
5. Review

## 4. Files
- TBD based on task

## 5. Verification
- Run verifier.py
- Check all endpoints

## 6. Risks
- AI gateway may fail
- Deploy may break

## 7. Approval
- [ ] User reviewed
"""


def phase_2_execution(plan_path):
    """Execute the plan (user-driven via AI in chat)."""
    log(f"PHASE 2: Execution — {plan_path.name}")
    log(f"  Plan ready for review at: {plan_path}")
    log(f"  AI assistant will execute this plan in the next chat turn.")
    log(f"  After execution, proceed to PHASE 3.")
    return True


def phase_3_verification():
    """Run verifier.py."""
    log("PHASE 3: Verification")
    verify_script = ENGINE_DIR / "engine" / "verifier.py"
    if not verify_script.exists():
        log(f"  verifier.py not found at {verify_script}")
        return False, "verifier missing"

    try:
        result = subprocess.run(
            [PYTHON, str(verify_script), str(ROOT / "verify_report.md")],
            cwd=str(ENGINE_DIR),
            capture_output=True, text=True, timeout=60,
        )
        passed = result.returncode == 0
        log(f"  -> {'PASS' if passed else 'FAIL'}: {result.stdout[-200:]}")
        return passed, result.stdout
    except Exception as e:
        log(f"  ERROR: {e}")
        return False, str(e)


def phase_4_review():
    """Run reviewer.py."""
    log("PHASE 4: Review")
    review_script = ENGINE_DIR / "engine" / "reviewer.py"
    if not review_script.exists():
        log(f"  reviewer.py not found")
        return False

    try:
        result = subprocess.run(
            [PYTHON, str(review_script), str(ROOT / "review_report.md")],
            cwd=str(ENGINE_DIR),
            capture_output=True, text=True, timeout=30,
        )
        log(f"  -> Report at: {ROOT / 'review_report.md'}")
        return result.returncode == 0
    except Exception as e:
        log(f"  ERROR: {e}")
        return False


def run_pipeline(task, max_retries=3):
    """Run the full 4-phase pipeline."""
    log(f"=== Pipeline Started: {task} ===")

    plan_path = phase_1_planning(task)
    phase_2_execution(plan_path)

    for attempt in range(1, max_retries + 1):
        log(f"--- Verification attempt {attempt}/{max_retries} ---")
        passed, msg = phase_3_verification()
        if passed:
            log(f"Verification PASSED on attempt {attempt}")
            break
        log(f"Verification FAILED on attempt {attempt}")
        if attempt < max_retries:
            log("Looping back to PHASE 2 — AI will fix the issues")

    phase_4_review()
    log(f"=== Pipeline Complete: {task} ===")
    log(f"Outputs:")
    log(f"  Plan: {plan_path}")
    log(f"  Verify: {ROOT / 'verify_report.md'}")
    log(f"  Review: {ROOT / 'review_report.md'}")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    args = sys.argv[1:]
    if "--loop" in args:
        idx = args.index("--loop")
        iterations = int(args[idx + 1]) if idx + 1 < len(args) else 1
        task = " ".join(a for a in args[:idx] if not a.startswith("--"))
        for i in range(iterations):
            log(f"=== Iteration {i+1}/{iterations} ===")
            run_pipeline(task)
    else:
        task = " ".join(args)
        run_pipeline(task)


if __name__ == "__main__":
    main()
